// features/interactions/ph-chips.js
// THE LIBRARIAN: Scans "dumb" chips, looks up data, and stamps attributes.
// Does NOT create DOM elements.

import { norm } from "../../src/data/phonemes/core.js";
import { getPhonemeAssetByIPA } from "../../src/data/phonemes/assets.js";
import { phonemeDetailsByIPA, articulatorPlacement } from "../../src/data/phonemes/details.js";

// Standard set to validate against
const KNOWN_PHONES = new Set([
  "p","b","t","d","k","g","m","n","f","v","s","z","h","l","ɹ","r","w","j","ŋ",
  "θ","ð","ʃ","ʒ","tʃ","dʒ","ɾ","ʔ","ʍ",
  "i","ɪ","e","ɛ","æ","ɑ","ɔ","o","ʊ","u","ʌ","ə","ɚ","ɝ",
  "eɪ","aɪ","ɔɪ","aʊ","oʊ",
  "iy","ih","eh","ae","aa","ao","ah","ax","axr","er","uw","uh","ey","ay","aw","ow","oy",
  "th","dh","sh","zh","ch","jh","dx","ng","hh","wh","q","y"
]);

export async function initPhonemeChipBehavior(containerSelector = "#prettyResult") {
  const root = document.querySelector(containerSelector);
  if (!root) return;

  // Find all chips that haven't been hydrated yet
  // We look for .phoneme-chip (generated by rows.js)
  const chips = [...root.querySelectorAll(".phoneme-chip:not([data-hydrated])")];
  
  if (!chips.length) return;

  for (const chip of chips) {
    // 1. Get IPA (Prefer attribute, fallback to text)
    const rawIpa = chip.getAttribute("data-ipa") || chip.textContent.trim().split(" ")[0];
    const key = norm(rawIpa); // Normalize (ax -> ə, etc)

    // 2. Mark processed
    chip.setAttribute("data-hydrated", "true");
    // Ensure the normalized key is set for the Hover module
    chip.setAttribute("data-ipa", key); 

    // 3. Lookup Data (The "Digging" part)
    // Priority: Specific Coaching Detail > General Articulation > Asset Label
    const detail = phonemeDetailsByIPA[key];
    const placement = articulatorPlacement[key];
    const asset = getPhonemeAssetByIPA(key);

    let tipPlain = "";
    let tipTech = "";
    let tipMistake = "";
    let displayIPA = "";
    let words = [];

    if (detail) {
      tipPlain = detail.tip || "";
      tipTech = detail.tech || "";          // (future field)
      tipMistake = detail.mistake || "";    // already present in many entries
      displayIPA = detail.ipa || "";

      // (future) examples array support — you can choose "words" or "examples" in details.js
      const arr = detail.words || detail.examples;
      if (Array.isArray(arr)) words = arr;
    } else if (placement) {
      // Fallback: keep today’s behavior, but treat it as “Plain”
      tipPlain = `${placement.label}. ${placement.tip}`;
      displayIPA = `/${key}/ (as in '${placement.example}')`;

      // Immediate benefit: at least 1 example shows right now
      if (placement.example) words = [placement.example];
    }

    // 4) Stamp Attributes (The Hover module reads these)
    // Legacy field (kept for safety): data-tip-text
    if (tipPlain) {
      chip.setAttribute("data-tip-plain", tipPlain);
      chip.setAttribute("data-tip-text", tipPlain); // backward-compatible
    }
    if (tipTech) chip.setAttribute("data-tip-tech", tipTech);
    if (tipMistake) chip.setAttribute("data-tip-mistake", tipMistake);

    if (words.length) {
      chip.setAttribute("data-tip-words", JSON.stringify(words.filter(Boolean).slice(0, 3)));
    }

    if (displayIPA) chip.setAttribute("data-display-ipa", displayIPA);
    
    if (asset?.video) {
        chip.setAttribute("data-video-src", asset.video);
        if (asset.poster) chip.setAttribute("data-poster-src", asset.poster);
    }
    if (asset?.videoFront) {
      chip.setAttribute("data-video-front-src", asset.videoFront);
    }
  }
  
  // Console log to confirm we cleaned up the "Old" ones
  // console.log(`[LUX] Hydrated ${chips.length} phoneme chips.`);
}
